name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Vet
        run: go vet ./...

  container-test:
    name: Container Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build Containerfile
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          file: ./Containerfile
          load: true
          tags: caddy-file-ip:test

      - name: Run container
        run: |
          docker run -d \
            --name caddy-test \
            -p 8080:8080 \
            -p 2019:2019 \
            -v ${{ github.workspace }}/test/ip-list.txt:/app/ip-list.txt:ro \
            -v ${{ github.workspace }}/test/Caddyfile:/app/Caddyfile:ro \
            caddy-file-ip:test \
            caddy run --config /app/Caddyfile --adapter caddyfile

      - name: Wait for Caddy to start
        run: sleep 5

      - name: Check Caddy is running
        run: docker logs caddy-test

      - name: Test endpoint
        run: |
          sleep 2
          curl -s --fail http://localhost:8080/ | grep -q "Hello"

      - name: Check admin endpoint for file source in trusted proxies
        run: |
          CONFIG=$(curl -s http://localhost:2019/config/)
          echo "${CONFIG}" | jq -r '.'
          # Check that trusted proxies is using the "file" source
          echo "${CONFIG}" | jq -e '.apps.http.servers.srv0.trusted_proxies.source == "file"'
          # Check that trusted proxies has files set and it is an array containing our configured file
          echo "${CONFIG}" | jq -e '.apps.http.servers.srv0.trusted_proxies.files == ["/app/ip-list.txt"]'

      - name: Stop and remove container
        if: always()
        run: |
          docker stop caddy-test || true
          docker rm caddy-test || true